# Dockerfile.dashboard
FROM python:3.11-slim

WORKDIR /app

RUN pip install streamlit pandas plotly pymongo pytz

COPY dashboards/ ./dashboards/

EXPOSE 8501

CMD ["streamlit", "run", "dashboards/streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]