FROM python:3.11-slim

WORKDIR /app

COPY ../requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ../src ./src
COPY ../.env .

# Commande qui maintient le conteneur en vie
CMD ["tail", "-f", "/dev/null"]
