FROM python:3.11-slim

WORKDIR /app

# Installation des dépendances
RUN pip install --no-cache-dir streamlit pandas plotly pymongo pytz python-dotenv

# Copie du dashboard
COPY ../dashboards/ ./dashboards/
COPY ../.env .

EXPOSE 8501

CMD ["streamlit", "run", "dashboards/streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]
